services:
  discord-bot:
    build: .
    image: discord-bot:prod
    container_name: discord-bot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    volumes:
      - bot-src:/app/src

volumes:
  bot-src:
